-------------------------------------------------------------------------------
Test set: UserApplicationTest
-------------------------------------------------------------------------------
Tests run: 2, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 23.418 s <<< FAILURE! - in UserApplicationTest
httpRequestTest(UserApplicationTest)  Time elapsed: 3.592 s  <<< ERROR!
java.lang.IllegalStateException: No instances available for localhost
	at UserApplicationTest.httpRequestTest(UserApplicationTest.java:35)

test1(UserApplicationTest)  Time elapsed: 1.375 s  <<< ERROR!
org.mybatis.spring.MyBatisSystemException: 
nested exception is org.apache.ibatis.exceptions.PersistenceException: 
### Error querying database.  Cause: org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection; nested exception is java.sql.SQLException: Access denied for user 'root'@'localhost' (using password: NO)
### The error may exist in cn/yun/cloud/dao/UserMapper.java (best guess)
### The error may involve cn.yun.cloud.dao.UserMapper.selectById
### The error occurred while executing a query
### Cause: org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection; nested exception is java.sql.SQLException: Access denied for user 'root'@'localhost' (using password: NO)
	at UserApplicationTest.test1(UserApplicationTest.java:28)
Caused by: org.apache.ibatis.exceptions.PersistenceException: 

### Error querying database.  Cause: org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection; nested exception is java.sql.SQLException: Access denied for user 'root'@'localhost' (using password: NO)
### The error may exist in cn/yun/cloud/dao/UserMapper.java (best guess)
### The error may involve cn.yun.cloud.dao.UserMapper.selectById
### The error occurred while executing a query
### Cause: org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection; nested exception is java.sql.SQLException: Access denied for user 'root'@'localhost' (using password: NO)
	at UserApplicationTest.test1(UserApplicationTest.java:28)
Caused by: org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection; nested exception is java.sql.SQLException: Access denied for user 'root'@'localhost' (using password: NO)
	at UserApplicationTest.test1(UserApplicationTest.java:28)
Caused by: java.sql.SQLException: Access denied for user 'root'@'localhost' (using password: NO)
	at UserApplicationTest.test1(UserApplicationTest.java:28)

